name: CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          # Revise Go version upon every minor release of Go
          go-version: "1.26.x"

      - name: Verify dependencies
        run: go mod verify

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -race -v ./...

