name: CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          # Revise Go version upon every minor release of Go (e.g. 1.24)
          go-version: "1.23.x"

      - name: Verify dependencies
        run: go mod verify

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -race -v ./...
